name: Code Style and Tests

on: push

jobs:
  code-style-and-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv
          coverage: none

      - name: Copy .env.example
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Laravel Pint Coding Style
        run: composer pint:fix -- --test

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Set Cache Permissions
        run: chmod -R 777 storage bootstrap/cache

      - name: Create SQLite Database
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Build Front End Assets
        run: npm ci && npm run build

      - name: Execute tests (Unit and Feature tests) via PHPUnit & Pest
        env:
          DB_CONNECTION: sqlite_testing
          DB_DATABASE: database/database.sqlite
        run: php artisan test
